# Generated by Django 4.1.7 on 2023-05-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_items_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Preparing', 'Preparing'), ('On the way', 'On the way'), ('Delievered', 'Delievered')], default='Preparing', max_length=50),
        ),
    ]
